// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PdfViewer: typeof import('./../src/components/PdfViewer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfUploader: typeof import('./../src/components/SelfUploader/index.vue')['default']
    SelfVanUploader: typeof import('./../src/components/SelfVanUploader/index.vue')['default']
    TitleBar: typeof import('./../src/components/TitleBar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanOverlay: typeof import('vant/es')['Overlay']
  }
}

export {}
